spring:
  datasource:
    url: jdbc:mysql://localhost:3307/game_list
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/db/*.xml
